"""Add missing nutrition and lifestyle health metrics

Revision ID: efa05fe6f34a
Revises: 02caa9073d27
Create Date: 2025-10-07 00:37:45.625708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa05fe6f34a'
down_revision = '02caa9073d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # These columns are now in the base schema (001_initial_schema)
    # This migration is kept for backwards compatibility but does nothing on fresh databases
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_data', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('social_interactions')
        batch_op.drop_column('screen_time_hours')
        batch_op.drop_column('meditation_minutes')
        batch_op.drop_column('bmi')
        batch_op.drop_column('diastolic_bp')
        batch_op.drop_column('systolic_bp')
        batch_op.drop_column('fiber_grams')
        batch_op.drop_column('fat_grams')
        batch_op.drop_column('carbs_grams')
        batch_op.drop_column('protein_grams')
        batch_op.drop_column('calories_consumed')

    # ### end Alembic commands ###
