"""Add missing nutrition and lifestyle health metrics

Revision ID: efa05fe6f34a
Revises: 02caa9073d27
Create Date: 2025-10-07 00:37:45.625708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa05fe6f34a'
down_revision = '02caa9073d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check what tables and columns exist (safe for fresh databases where initial schema already created these)
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    # Only alter health_data if it exists
    if 'health_data' in existing_tables:
        # Check which columns already exist
        columns = [col['name'] for col in inspector.get_columns('health_data')]
        
        with op.batch_alter_table('health_data', schema=None) as batch_op:
            # Only add columns that don't already exist (initial schema may have created them)
            if 'calories_consumed' not in columns:
                batch_op.add_column(sa.Column('calories_consumed', sa.Integer(), nullable=True))
            if 'protein_grams' not in columns:
                batch_op.add_column(sa.Column('protein_grams', sa.Float(), nullable=True))
            if 'carbs_grams' not in columns:
                batch_op.add_column(sa.Column('carbs_grams', sa.Float(), nullable=True))
            if 'fat_grams' not in columns:
                batch_op.add_column(sa.Column('fat_grams', sa.Float(), nullable=True))
            if 'fiber_grams' not in columns:
                batch_op.add_column(sa.Column('fiber_grams', sa.Float(), nullable=True))
            if 'systolic_bp' not in columns:
                batch_op.add_column(sa.Column('systolic_bp', sa.Integer(), nullable=True))
            if 'diastolic_bp' not in columns:
                batch_op.add_column(sa.Column('diastolic_bp', sa.Integer(), nullable=True))
            if 'bmi' not in columns:
                batch_op.add_column(sa.Column('bmi', sa.Float(), nullable=True))
            if 'meditation_minutes' not in columns:
                batch_op.add_column(sa.Column('meditation_minutes', sa.Integer(), nullable=True))
            if 'screen_time_hours' not in columns:
                batch_op.add_column(sa.Column('screen_time_hours', sa.Float(), nullable=True))
            if 'social_interactions' not in columns:
                batch_op.add_column(sa.Column('social_interactions', sa.Integer(), nullable=True))
            if 'notes' not in columns:
                batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_data', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('social_interactions')
        batch_op.drop_column('screen_time_hours')
        batch_op.drop_column('meditation_minutes')
        batch_op.drop_column('bmi')
        batch_op.drop_column('diastolic_bp')
        batch_op.drop_column('systolic_bp')
        batch_op.drop_column('fiber_grams')
        batch_op.drop_column('fat_grams')
        batch_op.drop_column('carbs_grams')
        batch_op.drop_column('protein_grams')
        batch_op.drop_column('calories_consumed')

    # ### end Alembic commands ###
